;; -*- mode: eask; lexical-binding: t -*-

(package "nerd-icons-buffer-menu"
         "0.1.0"
         "Display nerd icons in `buffer-menu'")

(website-url "https://github.com/jcs-elpa/nerd-icons-buffer-menu")
(keywords "frames")

(package-file "nerd-icons-buffer-menu.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
(depends-on "nerd-icons" "0.0.1")
(depends-on "noflet" "0.0.15")
(depends-on "msgu" "0.1.0")
